### ISSUE TITLE
您好，我非常想使用这个插件，安装后crodova闪退，请问你之后还更新过这个插件吗？

### ISSUE THREAD

**Issue by leekeal** [mljsgto222/cordova-plugin-bugly-upgrade#1]

**Comment by mljsgto222** [comment]
这个插件在我们这边几台android测试机上都没有问题，你可以提供下机器型号和logcat信息方便我排查吗？如果有问题的话我可以修复下

**Comment by leekeal** [comment]
谢谢，问题已经解决。
` <framework src="com.android.support:support-v4:26+" />`
缺少了这个。

**Comment by mljsgto222** [comment]
gj
